name: Generate Pacman Animation

on:
  schedule:
    - cron: "0 */12 * * *"
  workflow_dispatch:

jobs:
  generate:
    permissions:
      contents: write
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: joshua-a-l/github-readme-pacman@main
        with:
          github_user_name: rnnascimento21
